#!/bin/bash
# Setup Guest Access for Audiobookshelf and Calibre-Web
# Run this script on the DigitalOcean droplet after docker-compose is running

echo "======================================"
echo "Setting up Guest Access for Libraries"
echo "======================================"

# Configuration
GUEST_USERNAME="guest"
GUEST_PASSWORD="GuestAccess2024!"
ABS_CONTAINER="raphaelshorizon-audiobookshelf-1"
CALIBRE_CONTAINER="raphaelshorizon-calibre-web-1"

echo ""
echo "Step 1: Setting up Audiobookshelf Guest Account"
echo "------------------------------------------------"

# Get Audiobookshelf admin token first (you'll need to set this manually after first login)
echo "IMPORTANT: After running this script, you need to:"
echo "1. Login to Audiobookshelf admin at /audiobookshelf/"
echo "2. Go to Settings > Users > Create User"
echo "3. Create user with:"
echo "   - Username: $GUEST_USERNAME"
echo "   - Password: $GUEST_PASSWORD"
echo "   - Type: User (not admin)"
echo "   - Permissions: Can access all libraries (read only)"
echo ""

echo "Step 2: Setting up Calibre-Web Guest Account"
echo "---------------------------------------------"
echo "IMPORTANT: For Calibre-Web, you need to:"
echo "1. Login to Calibre-Web admin at /calibre/"
echo "2. Go to Admin > Users > Add New User"
echo "3. Create user with:"
echo "   - Username: $GUEST_USERNAME"
echo "   - Password: $GUEST_PASSWORD"
echo "   - Role: User (not admin)"
echo "   - Check: Can Download Books"
echo ""
echo "OR enable Anonymous Browsing:"
echo "1. Go to Admin > Basic Configuration > Feature Configuration"
echo "2. Enable 'Allow Anonymous Browsing'"
echo ""

echo "======================================"
echo "After Setup Verification"
echo "======================================"
echo ""
echo "Test the guest login by running:"
echo ""
echo "# Test Audiobookshelf:"
echo "curl -X POST http://localhost:13378/login \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"username\":\"$GUEST_USERNAME\",\"password\":\"$GUEST_PASSWORD\"}'"
echo ""
echo "# Test Calibre-Web:"
echo "curl -X POST http://localhost:8083/login \\"
echo "  -H 'Content-Type: application/x-www-form-urlencoded' \\"
echo "  -d 'username=$GUEST_USERNAME&password=$GUEST_PASSWORD'"
echo ""
echo "======================================"
echo "Done!"
echo "======================================"
